name: wagmi_flutter_web
description: "Wagmi JS SDK wrapper for Dart Web"
version: 0.0.1-dev.1
homepage: https://github.com/archethic-foundation/wagmi_flutter_web

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.4

dev_dependencies:
  build_runner: ^2.4.8
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2

flutter:
  uses-material-design: true
